version: '3.5'
services:
  php_cli:
    image: af.flyeralarm/newproject/php_cli:dev
    working_dir: /var/www/html
    volumes:
      - ./../../code:/var/www/html
    environment:
      - VHOST=localhost